/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"


int
calculadora_prog_1(char *host, int operacion, struct numeros numbers)
{
	CLIENT *clnt;
	int  *result;

#ifndef	DEBUG
	clnt = clnt_create (host, CALCULADORA_PROG, CALCULADORA_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	switch(operacion){
		case 1:
			result = suma_1(&numbers, clnt);
		
			if (result == (int *) NULL) {
				clnt_perror (clnt, "call failed");
			}
		
			printf("La suma es: %d\n", *result);
			break;
		case 2:
			result = resta_1(&numbers, clnt);
		
			if (result == (int *) NULL) {
				clnt_perror (clnt, "call failed");
			}

			printf("La resta es: %d\n", *result);
			break;
		case 3:
			result = multiplicacion_1(&numbers, clnt);
		
			if (result == (int *) NULL) {
				clnt_perror (clnt, "call failed");
			}		
		
			printf("La multiplicacion es: %d\n", *result);
			break;
		case 4:
			result = division_1(&numbers, clnt);
		
			if (result == (int *) NULL) {
				clnt_perror (clnt, "call failed");
			}
			
			printf("La division es: %d\n", *result);
			break;
		default:
			break;
	}
	
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	
	numeros numbers;
	
	int operaciones;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	
	printf("Introduzca la operacion a realizar:\n");
	printf(" 1 = suma\n");
	printf(" 2 = resta\n");
	printf(" 3 = multiplicacion\n");
	printf(" 4 = division\n");
	scanf("%d", &operaciones);
	
	while(operaciones>4 || operaciones<1){
		printf("Error, debe introducir un numero entre 1 y 4: ");
		scanf("%d\n", &operaciones);
	}
	
	host = argv[1];
	
	printf("Introduzca el primer numero:\n");
	scanf("%d", &numbers.a);
	printf("Introduzca el segundo numero:\n");
	scanf("%d", &numbers.b);
	
	int result;
	
	result = calculadora_prog_1 (host, operaciones, numbers);
exit (0);
}
