/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"
#include <time.h>

int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	
	int numero1;
	int numero2;
	
	printf("Introduzca el primer numero que desea sumar:\n");
	scanf("%d", &numero1);
	printf("Introduzca el segundo numero:\n");
	scanf("%d", &numero2);
	
	CLIENT *clnt;


#ifndef	DEBUG
	clnt = clnt_create(host, CALCULADORA_PROG, CALCULADORA_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
	
#endif /*DEBUG*/

	int *result;
	int resultado=0;
	
	numeros numeros = {numero1, numero2};
	
	clock_t begin = clock();
	
	for(int i=0; i<100000; i++){
		result = suma_1(&numeros, clnt);
		if(result==(int*)NULL){
			clnt_perror(clnt, "call failed");
		}
		resultado = resultado + *result;
	}
	
	clock_t end = clock();

	double time;

	time = (double)(end-begin) / CLOCKS_PER_SEC;

	printf("La suma es %d, y el tiempo consumido es %f segundos\n", resultado, time);


#ifndef	DEBUG
	clnt_destroy (clnt);	
#endif	 /* DEBUG */
	exit (0);
}
